const newTool = [
    {
        id: 0,
        language: 'JAVASCRIPT',
        icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/javascript/javascript-original.svg',
        desc: 'Programming language that is one of the core technologies of the World Wide Web.',
        longDesc: 'JavaScript, often abbreviated JS, is a programming language that is one of the core technologies of the World Wide Web, alongside HTML and CSS. As of 2022, 98% of websites use JavaScript on the client side for web page behavior, often incorporating third-party libraries. All major web browsers have a dedicated JavaScript engine to execute the code on users devices.',
        resource1: 'Wikipedia',
        link1: 'https://en.wikipedia.org/wiki/JavaScript',
        resource2: '',
        link2: '',
        resource3: '',
        link3: '',
    },
    {
        id: 1,
        language: 'REACT',
        icon: 'https://icon-library.com/images/react-icon/react-icon-15.jpg',
        desc: 'React is a free and open-source front-end JavaScript library ',
        longDesc: 'React (also known as React.js or ReactJS) is a free and open-source front-end JavaScript library for building user interfaces based on UI components. It is maintained by Meta (formerly Facebook) and a community of individual developers and companies.React can be used as a base in the development of single-page, mobile, or server-rendered applications with frameworks like Next.js. However, React is only concerned with state management and rendering that state to the DOM, so creating React applications usually requires the use of additional libraries for routing, as well as certain client-side functionality.',
        resource1: 'Wikipedia',
        link1: 'https://en.wikipedia.org/wiki/React_(JavaScript_library',
        resource2: '',
        link2: '',
        resource3: '',
        link3: '',
    },
    {
        id: 2,
        language: 'ANGULAR',
        icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/angularjs/angularjs-original.svg',
        desc: 'Angular is a TypeScript-based open-source web application framework ',
        longDesc: 'Angular (commonly referred to as "Angular 2+" or "Angular CLI") is a TypeScript-based free and open-source web application framework led by the Angular Team at Google and by a community of individuals and corporations. Angular is a complete rewrite from the same team that built AngularJS.',
        resource1: 'Wikipedia',
        link1: 'https://en.wikipedia.org/wiki/Angular_(web_framework)',
        resource2: '',
        link2: '',
        resource3: '',
        link3: '',
    },
    {
        id: 3,
        language: 'VUE',
        icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/vuejs/vuejs-original.svg',
        desc: 'Vue.js is a model–view–viewmodel front end JavaScript framework',
        longDesc: 'Vue.js (commonly referred to as Vue; pronounced "view") is an open-source model–view–viewmodel front end JavaScript framework for building user interfaces and single-page applications. It was created by Evan You, and is maintained by him and the rest of the active core team members',
        resource1: 'Wikipedia',
        link1: 'https://en.wikipedia.org/wiki/Vue.js',
        resource2: '',
        link2: '',
        resource3: '',
        link3: '',
      },
    {
        id: 4,
        language: 'DENO',
        icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/denojs/denojs-original.svg',
        desc: 'Deno is a runtime for JavaScript, TypeScript, and WebAssembly',
        longDesc: `Deno is a runtime for JavaScript, TypeScript, and WebAssembly that is based on the V8 JavaScript engine and the Rust programming language. Deno was co-created by Ryan Dahl, who also created Node.js.`,
        resource1: 'Wikipedia',
        link1: 'https://en.wikipedia.org/wiki/Deno_(software)',
        resource2: '',
        link2: '',
        resource3: '',
        link3: '',
    },
    {
        id: 5,
        language: 'CSS',
        icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/css3/css3-original.svg',
        desc: 'Cascading Style Sheets (CSS) is a style sheet language',
        longDesc: `Cascading Style Sheets (CSS) is a style sheet language used for describing the presentation of a document written in a markup language such as HTML or XML (including XML dialects such as SVG, MathML or XHTML). CSS is a cornerstone technology of the World Wide Web, alongside HTML and JavaScript.`,
        resource1: 'Wikipedia',
        link1: 'https://en.wikipedia.org/wiki/CSS',
        resource2: '',
        link2: '',
        resource3: '',
        link3: '',
    },
    {
        id: 6,
        language: 'NODE',
        icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nodejs/nodejs-original-wordmark.svg',
        desc: 'Node.js is an open-source, cross-platform, back-end JavaScript runtime environment',
        longDesc: `Node.js is an open-source, cross-platform, back-end JavaScript runtime environment that runs on the V8 engine and executes JavaScript code outside a web browser, which was designed to build scalable network applications. Node.js lets developers use JavaScript to write command line tools and for server-side scripting—running scripts server-side to produce dynamic web page content before the page is sent to the user's web browser. Consequently, Node.js represents a "JavaScript everywhere" paradigm, unifying web-application development around a single programming language, rather than different languages for server-side and client-side scripts.`,
        resource1: 'Wikipedia',
        link1: 'https://en.wikipedia.org/wiki/Node.js',
        resource2: '',
        link2: '',
        resource3: '',
        link3: '',
    },
    {
        id: 7,
        language: 'HTML',
        icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/html5/html5-original.svg',
        desc: 'HTML is the language for describing the structure of Web pages.',
        longDesc: 'The HyperText Markup Language or HTML is the standard markup language for documents designed to be displayed in a web browser. It can be assisted by technologies such as Cascading Style Sheets (CSS) and scripting languages such as JavaScript.',
        resource1: 'Wikipedia',
        link1: 'https://en.wikipedia.org/wiki/HTML#:~:text=The%20HyperText%20Markup%20Language%20or,(HyperText%20Markup%20Language)',
        resource2: '',
        link2: '',
        resource3: '',
        link3: '',
    },

]
